seed: 42
device: auto
strategy: None # (redundant) categorical or temperature-sampling
temperature: 0.1 # controls strategy: greedy if temperature <= 0, categorical if temperature = 1.0, tempareture-scaled categorical otherwise.
data:
  l: 256
  train_split: 0.9
  batch_size: 128
  grammar: anbn
model:
  architecture: autoregressive # classic (torch-native) or v2 (QKV low-level) or RPE or FIRE or autoregressive
  max_len: 258       
  vocab_size: 5
  n_head: 4
  n_layers: 7
  embed_dim: 128
  dim_feedforward: 1024
  dropout: 0.1
  layer_norm_eps: 0.006
  T: 0 # set to 0 if using autoregressive architecture; otherwise, the number of diffusion steps
  sampling_eps: 0.00001
  eos_weight: 10.0
  inverse_t: False
training:
  epochs: 100000
  learning_rate: 0.002
  num_warmup_steps: 1000
  weight_decay: 0.0
  loss_type: cross_entropy # eq8, eq9, or cross_entropy (for autoregressive)
  denoise: "0" # "0" or eps
validation:
  val_every: 1000
evaluation:
  eval_every: 5000
  n_samples: 200
  eval_dataset: complete # limited or randomised or complete
  eval_type: full # full or random
  cutoff: 258 # max prediction length cutoff (for autoregressive only)
wandb:
  project: "discrete-diffusion"
  group: "AR"
paths:
  models_dir: models
  figures_dir: figures
  experiment_name: AR_larger
notes: "Testing a larger AR model"
