seed: 41
device: cuda
data:
  l: 256
  train_split: 0.9
  batch_size: 64
  grammar: anbn
model:
  max_len: 258       
  vocab_size: 6
  n_head: 4
  n_layers: 4
  embed_dim: 128
  dim_feedforward: 128
  dropout: 0.1
  T: 1500
  eos_weight: 10.0
training:
  epochs: 30000
  learning_rate: 0.001
  weight_decay: 0.0
evaluation:
  eval_every: 500
  n_samples: 100
  samples_type: random
  eval_type: autoregressive
paths:
  models_dir: models
  figures_dir: figures
  experiment_name: full_denoising_output_log_t=1500_variable_seeds
notes: "Investigating seed effect on evaluation (pre-trained model remains the same)"
