seed: 42
device: auto
strategy: None # (redundant) categorical or temperature-sampling
temperature: 1.0 # controls strategy: greedy if temperature <= 0, categorical if temperature = 1.0, tempareture-scaled categorical otherwise.
data:
  l: 256
  train_split: 0.9
  batch_size: 64
  grammar: anbn
model:
  architecture: oracle # classic (torch-native) or v2 (QKV low-level) or RPE or FIRE
  max_len: 258       
  vocab_size: 6
  n_head: 4
  n_layers: 4
  embed_dim: 256
  dim_feedforward: 1024
  dropout: 0.1
  layer_norm_eps: 0.0002
  sampling_eps: 0.00001
  sigma: 40.0
  eos_weight: 2.0
  inverse_t: False
training:
  epochs: 50000
  learning_rate: 0.001
  num_warmup_steps: 1000
  weight_decay: 0.01
  loss_type: eq8 # eq8 or eq9
  gaussian_noise: True
  denoise: "0" # "0" or eps
schedule:
  type: categorical  # categorical or gaussian
  sigma: 1.0         # Gaussian width parameter; ignored when type=categorical
validation:
  val_every: 1000
evaluation:
  eval_every: 4000
  n_samples: 500
  eval_dataset: unconditional # limited or randomised or complete
  eval_type: random # full or random
  cutoff: 258
investigation:
  n_first_tokens: 258 # how many first tokens to investigate the distribution of
  store_numeric: True # whether to store numeric logs of the investigation
wandb:
  project: "discrete-diffusion"
  group: "Gaussian-RPE"
paths:
  models_dir: models
  figures_dir: figures
  experiment_name: Oracle-T-sweep-complete
notes: "Investigate oracle model with varying number of denoising steps (T) to see how it affects a perfect predictor"
