seed: 42
device: auto
decoding_strategy: schedule_driven
sampling_strategy: categorical
temperature: 0.00001  # logit scaling temperature
data:
  l: 256
  train_split: 0.9
  batch_size: 64
  grammar: anbn
model:
  architecture: RPE_KQ # classic (torch-native) or v2 (QKV low-level) or RPE or FIRE
  max_len: 258       
  vocab_size: 6
  n_head: 4
  n_layers: 4
  embed_dim: 256
  dim_feedforward: 1024
  dropout: 0.1
  layer_norm_eps: 0.0002
  T: 500
  sampling_eps: 0.00001
  eos_weight: 10.0
  inverse_t: False
training:
  epochs: 100000
  learning_rate: 0.001
  num_warmup_steps: 1000
  weight_decay: 0.0
  loss_type: eq8 # eq8 or eq9
  denoise: "0" # "0" or eps
validation:
  val_every: 1000
evaluation:
  eval_every: 5000
  n_samples: 200
  eval_dataset: complete # limited or randomised or complete
  eval_type: full # full or random
  cutoff: 258
investigation:
  n_first_tokens: 258 # how many first tokens to investigate the distribution of
  store_numeric: True # whether to store numeric logs of the investigation
wandb:
  project: "discrete-diffusion"
  group: "RPE-architecture-fixed"
paths:
  models_dir: models
  figures_dir: figures
  experiment_name: RPE-full-RPE
notes: "Decrease temp (0.00001) for RPE architecture to investigate the almost greedy regime"
